export interface RoadmapTask {
  id: string;
  day: number;
  title: string;
  description: string;
  topic: string;
  duration: string;
  difficulty: "Easy" | "Medium" | "Hard";
  resources: { label: string; url: string }[];
  type: "study" | "practice" | "mock" | "review";
}

export interface RoadmapWeek {
  week: number;
  theme: string;
  focus: string;
  color: string;
  tasks: RoadmapTask[];
}

export const ROADMAP_DATA: RoadmapWeek[] = [
  {
    week: 1,
    theme: "Foundation",
    focus: "Data Structures & Core Concepts",
    color: "purple",
    tasks: [
      {
        id: "d1",
        day: 1,
        title: "Arrays & Strings Mastery",
        description: "Two pointers, sliding window, prefix sums. Solve 5 LeetCode easy problems.",
        topic: "DSA",
        duration: "2h",
        difficulty: "Easy",
        type: "study",
        resources: [
          { label: "NeetCode Arrays", url: "https://neetcode.io" },
          { label: "LeetCode Arrays", url: "https://leetcode.com/tag/array" },
        ],
      },
      {
        id: "d2",
        day: 2,
        title: "Linked Lists Deep Dive",
        description: "Singly, doubly, circular. Reverse, detect cycle, merge sorted lists.",
        topic: "DSA",
        duration: "2h",
        difficulty: "Easy",
        type: "study",
        resources: [
          { label: "Visualgo", url: "https://visualgo.net/en/list" },
          { label: "LeetCode Linked List", url: "https://leetcode.com/tag/linked-list" },
        ],
      },
      {
        id: "d3",
        day: 3,
        title: "Stacks & Queues",
        description: "Monotonic stack, queue using stacks, BFS foundations.",
        topic: "DSA",
        duration: "1.5h",
        difficulty: "Easy",
        type: "practice",
        resources: [
          { label: "Stack Problems", url: "https://leetcode.com/tag/stack" },
        ],
      },
      {
        id: "d4",
        day: 4,
        title: "Hash Maps & Sets",
        description: "Frequency counting, two-sum pattern, anagram detection.",
        topic: "DSA",
        duration: "2h",
        difficulty: "Easy",
        type: "study",
        resources: [
          { label: "Hash Table Problems", url: "https://leetcode.com/tag/hash-table" },
        ],
      },
      {
        id: "d5",
        day: 5,
        title: "Trees — BFS & DFS",
        description: "Binary trees, level order traversal, path sum, diameter.",
        topic: "DSA",
        duration: "2.5h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "Tree Visualizer", url: "https://visualgo.net/en/bst" },
          { label: "LeetCode Trees", url: "https://leetcode.com/tag/tree" },
        ],
      },
      {
        id: "d6",
        day: 6,
        title: "Week 1 Mock Interview",
        description: "30-min timed session on arrays + trees. Use AI Interview Hacker.",
        topic: "Mock",
        duration: "1h",
        difficulty: "Medium",
        type: "mock",
        resources: [],
      },
      {
        id: "d7",
        day: 7,
        title: "Week 1 Review & Gaps",
        description: "Re-solve problems you got wrong. Read solutions for hard ones.",
        topic: "Review",
        duration: "1.5h",
        difficulty: "Easy",
        type: "review",
        resources: [],
      },
    ],
  },
  {
    week: 2,
    theme: "Algorithms",
    focus: "Sorting, Searching & Dynamic Programming",
    color: "blue",
    tasks: [
      {
        id: "d8",
        day: 8,
        title: "Binary Search Patterns",
        description: "Search in rotated array, find peak, binary search on answer.",
        topic: "Algorithms",
        duration: "2h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "Binary Search Guide", url: "https://leetcode.com/tag/binary-search" },
        ],
      },
      {
        id: "d9",
        day: 9,
        title: "Recursion & Backtracking",
        description: "Subsets, permutations, N-Queens, Sudoku solver.",
        topic: "Algorithms",
        duration: "2.5h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "Backtracking Patterns", url: "https://leetcode.com/tag/backtracking" },
        ],
      },
      {
        id: "d10",
        day: 10,
        title: "Dynamic Programming — 1D",
        description: "Fibonacci, climbing stairs, house robber, coin change.",
        topic: "DP",
        duration: "3h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "DP for Beginners", url: "https://leetcode.com/discuss/general-discussion/458695" },
        ],
      },
      {
        id: "d11",
        day: 11,
        title: "Dynamic Programming — 2D",
        description: "Longest common subsequence, edit distance, knapsack.",
        topic: "DP",
        duration: "3h",
        difficulty: "Hard",
        type: "study",
        resources: [
          { label: "2D DP Problems", url: "https://leetcode.com/tag/dynamic-programming" },
        ],
      },
      {
        id: "d12",
        day: 12,
        title: "Graphs — BFS & DFS",
        description: "Number of islands, clone graph, course schedule (topological sort).",
        topic: "Graphs",
        duration: "2.5h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "Graph Algorithms", url: "https://visualgo.net/en/dfsbfs" },
        ],
      },
      {
        id: "d13",
        day: 13,
        title: "Week 2 Mock Interview",
        description: "45-min session: DP + Graph problem. Focus on explaining approach.",
        topic: "Mock",
        duration: "1h",
        difficulty: "Hard",
        type: "mock",
        resources: [],
      },
      {
        id: "d14",
        day: 14,
        title: "Week 2 Review",
        description: "Revisit DP patterns. Write cheat sheet of patterns you know.",
        topic: "Review",
        duration: "1.5h",
        difficulty: "Easy",
        type: "review",
        resources: [],
      },
    ],
  },
  {
    week: 3,
    theme: "System Design",
    focus: "Architecture, Scalability & Design Patterns",
    color: "cyan",
    tasks: [
      {
        id: "d15",
        day: 15,
        title: "System Design Fundamentals",
        description: "CAP theorem, load balancing, caching, CDN, databases.",
        topic: "System Design",
        duration: "2h",
        difficulty: "Medium",
        type: "study",
        resources: [
          { label: "System Design Primer", url: "https://github.com/donnemartin/system-design-primer" },
        ],
      },
      {
        id: "d16",
        day: 16,
        title: "Design URL Shortener",
        description: "Hash functions, database schema, read/write ratio, scaling.",
        topic: "System Design",
        duration: "2h",
        difficulty: "Medium",
        type: "practice",
        resources: [
          { label: "Grokking System Design", url: "https://www.educative.io/courses/grokking-the-system-design-interview" },
        ],
      },
      {
        id: "d17",
        day: 17,
        title: "Design Twitter / News Feed",
        description: "Fan-out on write vs read, timeline generation, ranking.",
        topic: "System Design",
        duration: "2.5h",
        difficulty: "Hard",
        type: "practice",
        resources: [],
      },
      {
        id: "d18",
        day: 18,
        title: "Behavioral Interview Prep",
        description: "STAR method. Prepare 10 stories: leadership, conflict, failure, success.",
        topic: "HR",
        duration: "2h",
        difficulty: "Easy",
        type: "study",
        resources: [
          { label: "STAR Method Guide", url: "https://www.themuse.com/advice/star-interview-method" },
        ],
      },
      {
        id: "d19",
        day: 19,
        title: "HR Mock Interview",
        description: "Practice 5 behavioral questions with AI. Focus on structure and clarity.",
        topic: "HR",
        duration: "1h",
        difficulty: "Medium",
        type: "mock",
        resources: [],
      },
      {
        id: "d20",
        day: 20,
        title: "Resume Polish",
        description: "Add missing keywords from analysis. Quantify 3 more achievements.",
        topic: "Resume",
        duration: "1.5h",
        difficulty: "Easy",
        type: "review",
        resources: [],
      },
      {
        id: "d21",
        day: 21,
        title: "Full Mock Interview",
        description: "1-hour full simulation: DSA + System Design + 2 behavioral questions.",
        topic: "Mock",
        duration: "1.5h",
        difficulty: "Hard",
        type: "mock",
        resources: [],
      },
    ],
  },
  {
    week: 4,
    theme: "Final Sprint",
    focus: "Company-Specific Prep & Confidence Building",
    color: "green",
    tasks: [
      {
        id: "d22",
        day: 22,
        title: "Company Research",
        description: "Study target company's tech stack, culture, recent news, products.",
        topic: "Research",
        duration: "1.5h",
        difficulty: "Easy",
        type: "study",
        resources: [
          { label: "Glassdoor Reviews", url: "https://glassdoor.com" },
          { label: "Blind", url: "https://teamblind.com" },
        ],
      },
      {
        id: "d23",
        day: 23,
        title: "Hard LeetCode Blitz",
        description: "Solve 3 hard problems from your weak topics. Time yourself.",
        topic: "DSA",
        duration: "3h",
        difficulty: "Hard",
        type: "practice",
        resources: [],
      },
      {
        id: "d24",
        day: 24,
        title: "System Design — Design Netflix",
        description: "Video streaming, CDN, recommendation engine, microservices.",
        topic: "System Design",
        duration: "2h",
        difficulty: "Hard",
        type: "practice",
        resources: [],
      },
      {
        id: "d25",
        day: 25,
        title: "Communication & Clarity",
        description: "Practice thinking out loud. Record yourself solving a problem.",
        topic: "Soft Skills",
        duration: "1.5h",
        difficulty: "Medium",
        type: "practice",
        resources: [],
      },
      {
        id: "d26",
        day: 26,
        title: "Final Mock — Company Specific",
        description: "Full interview simulation tailored to your target company.",
        topic: "Mock",
        duration: "1.5h",
        difficulty: "Hard",
        type: "mock",
        resources: [],
      },
      {
        id: "d27",
        day: 27,
        title: "Weak Areas Final Review",
        description: "Go through your lowest-scoring topics one more time.",
        topic: "Review",
        duration: "2h",
        difficulty: "Medium",
        type: "review",
        resources: [],
      },
      {
        id: "d28",
        day: 28,
        title: "Rest & Mental Prep",
        description: "Light review only. Sleep well. You are ready.",
        topic: "Wellness",
        duration: "30min",
        difficulty: "Easy",
        type: "review",
        resources: [],
      },
    ],
  },
];

export const SKILL_GAPS = [
  { skill: "Dynamic Programming", score: 48, priority: "High",   color: "#ef4444", bg: "bg-red-500/10",    border: "border-red-500/20" },
  { skill: "System Design",       score: 55, priority: "High",   color: "#f59e0b", bg: "bg-yellow-500/10", border: "border-yellow-500/20" },
  { skill: "Graph Algorithms",    score: 62, priority: "Medium", color: "#f59e0b", bg: "bg-yellow-500/10", border: "border-yellow-500/20" },
  { skill: "Behavioral (STAR)",   score: 70, priority: "Medium", color: "#8b5cf6", bg: "bg-purple-500/10", border: "border-purple-500/20" },
  { skill: "Binary Search",       score: 74, priority: "Low",    color: "#10b981", bg: "bg-emerald-500/10",border: "border-emerald-500/20" },
];

export const AI_TIPS = [
  "You're making great progress! DP is tough — consistency beats intensity.",
  "Try explaining solutions out loud. It reveals gaps you didn't know existed.",
  "One mock interview per week is more valuable than 10 hours of passive reading.",
  "Focus on patterns, not memorization. There are only ~15 core DSA patterns.",
  "Your communication score is your biggest differentiator at senior levels.",
];
